// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates draft replies based on email content, extracted information, and knowledge base chunks using AI.
 *
 * - generateDraftReply - A function that handles the generation of draft replies.
 * - GenerateDraftReplyInput - The input type for the generateDraftReply function.
 * - GenerateDraftReplyOutput - The return type for the generateDraftReply function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDraftReplyInputSchema = z.object({
  emailContent: z.string().describe('The content of the email to reply to.'),
  extractedInfo: z.string().describe('Extracted information from the email, such as phone numbers or product names.'),
  knowledgeBaseChunks: z.string().describe('Relevant knowledge base chunks to help generate the reply.'),
});
export type GenerateDraftReplyInput = z.infer<typeof GenerateDraftReplyInputSchema>;

const GenerateDraftReplyOutputSchema = z.object({
  draftText: z.string().describe('The generated draft reply text.'),
});
export type GenerateDraftReplyOutput = z.infer<typeof GenerateDraftReplyOutputSchema>;

export async function generateDraftReply(input: GenerateDraftReplyInput): Promise<GenerateDraftReplyOutput> {
  return generateDraftReplyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDraftReplyPrompt',
  input: {schema: GenerateDraftReplyInputSchema},
  output: {schema: GenerateDraftReplyOutputSchema},
  prompt: `You are an AI assistant helping to draft email replies.

  Based on the email content, extracted information, and knowledge base chunks provided, generate a draft reply that is helpful and relevant.

  Email Content: {{{emailContent}}}
  Extracted Information: {{{extractedInfo}}}
  Knowledge Base Chunks: {{{knowledgeBaseChunks}}}

  Draft Reply:`, 
});

const generateDraftReplyFlow = ai.defineFlow(
  {
    name: 'generateDraftReplyFlow',
    inputSchema: GenerateDraftReplyInputSchema,
    outputSchema: GenerateDraftReplyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
