import type { Email } from './types';

export const mockEmails: Email[] = [
  {
    id: '1',
    sender: 'Aakash Kannan',
    email: 'aakashkannan@gmail.com',
    avatar: 'https://picsum.photos/id/237/40/40',
    subject: 'Question about our last meeting',
    body: `Hi Team,\n\nI had a question regarding the action items from our last meeting. Could someone clarify the deadline for the Q3 report? I want to make sure I'm on track.\n\nWe discussed the preliminary data analysis, the client feedback session, and the new marketing strategy. I have my notes on the first two, but I seem to have missed the final decision on the Q3 report deadline. Any clarification would be greatly appreciated so I can plan my week accordingly.\n\nThanks,\nAakash`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 5),
    sentiment: 'neutral',
    priority: 'medium',
    status: 'pending',
  },
  {
    id: '2',
    sender: 'Priya Venkatesh',
    email: 'priya.v@example.com',
    avatar: 'https://picsum.photos/id/238/40/40',
    subject: 'Urgent: Server is down!',
    body: `Hello Support,\n\nThe main production server seems to be unresponsive. We're getting 500 errors across all services, and our primary customer portal is completely inaccessible. This is critical and needs immediate attention! Our clients are unable to log in, and it's impacting our business operations significantly.\n\nPlease investigate this as the highest priority and provide an ETA for a fix.\n\nRegards,\nPriya`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 30),
    sentiment: 'negative',
    priority: 'high',
    status: 'pending',
  },
  {
    id: '3',
    sender: 'Karthik Raja',
    email: 'karthik.r@example.com',
    avatar: 'https://picsum.photos/id/239/40/40',
    subject: 'Fantastic work on the new feature!',
    body: `Hi Dev Team,\n\nI just wanted to reach out and say thank you for the incredible work on the new data visualization feature. It's intuitive, fast, and our clients are already loving it. The ability to drill down into the data points is particularly impressive. Amazing job! This is a huge step forward for our product.\n\nBest,\nKarthik`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    sentiment: 'positive',
    priority: 'low',
    status: 'resolved',
  },
  {
    id: '4',
    sender: 'Meena Iyer',
    email: 'meena.i@example.com',
    avatar: 'https://picsum.photos/id/240/40/40',
    subject: 'Your subscription is expiring soon',
    body: `Dear customer,\n\nThis is a reminder that your subscription to our service will expire in 7 days. To ensure uninterrupted access to our premium features, please take a moment to renew your plan. You can do so by visiting the billing section of your account.\n\nThank you for being a valued customer,\nBilling Team`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    sentiment: 'neutral',
    priority: 'medium',
    status: 'resolved',
  },
  {
    id: '5',
    sender: 'Arun Pandian',
    email: 'arun.p@example.com',
    avatar: 'https://picsum.photos/id/241/40/40',
    subject: 'Feedback on the beta program',
    body: `Hi,\n\nI've been testing the beta version for the past week. I found a few bugs related to the export functionality, specifically when exporting to CSV format with more than 1000 rows. I've attached a document with screenshots and detailed steps to reproduce the issue. Overall, it's a great improvement and the new UI is very clean, but these issues are a bit frustrating for power users.\n\nHope this helps,\nArun`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    sentiment: 'negative',
    priority: 'medium',
    status: 'pending',
  },
  {
    id: '6',
    sender: 'Lakshmi Devi',
    email: 'lakshmi.d@example.com',
    avatar: 'https://picsum.photos/id/242/40/40',
    subject: 'Re: Project Alpha Kick-off',
    body: `Sounds good, I'm available at the proposed time. I've also added the preliminary agenda to the calendar invite. Looking forward to connecting with everyone and getting this project started.\n\n- Lakshmi`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 26),
    sentiment: 'positive',
    priority: 'low',
    status: 'resolved',
  },
  {
    id: '7',
    sender: 'Saravanan Murugan',
    email: 'saravanan.m@example.com',
    avatar: 'https://picsum.photos/id/243/40/40',
    subject: 'Invoice #54321 overdue',
    body: `Hi there,\n\nJust a friendly reminder that invoice #54321, for the amount of $1,250, is now past its due date of October 25th. Please process the payment at your earliest convenience to avoid any service interruptions. The attached PDF contains the full invoice details.\n\nIf you have any questions or have already made the payment, please disregard this message.\n\nThanks,\nSaravanan`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    sentiment: 'negative',
    priority: 'high',
    status: 'pending',
  },
  {
    id: '8',
    sender: 'Anitha Selvam',
    email: 'anitha.s@example.com',
    avatar: 'https://picsum.photos/id/244/40/40',
    subject: 'Lunch next week?',
    body: `Hey,\n\nAre you free for lunch sometime next week? I'd love to catch up and discuss the new marketing campaign I'm working on. I think you'd have some great insights. Let me know what day works for you.\n\nCheers,\nAnitha`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    sentiment: 'neutral',
    priority: 'low',
    status: 'resolved',
  },
  {
    id: '9',
    sender: 'Ganesh Kumar',
    email: 'ganesh.k@example.com',
    avatar: 'https://picsum.photos/id/245/40/40',
    subject: 'Quick question about the API documentation',
    body: `Hello,\n\nI was going through the API documentation for the new endpoint, and I noticed that the rate limits are not specified. Could you please provide that information? Also, is there a sandbox environment available for testing?\n\nThis would be very helpful for our integration planning.\n\nBest,\nGanesh`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    sentiment: 'neutral',
    priority: 'medium',
    status: 'pending',
  },
  {
    id: '10',
    sender: 'Deepa Krishnan',
    email: 'deepa.k@example.com',
    avatar: 'https://picsum.photos/id/246/40/40',
    subject: 'Your recent purchase',
    body: `Hi Deepa,\n\nThank you for your recent purchase from our store! We hope you're enjoying your new items. Would you mind taking a moment to leave a review? Your feedback helps us and other customers.\n\nHere is a link to leave your feedback: [link]\n\nWe appreciate your business!\n\nSincerely,\nThe Customer Success Team`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
    sentiment: 'positive',
    priority: 'low',
    status: 'resolved',
  },
  {
    id: '11',
    sender: 'Rajesh Nair',
    email: 'rajesh.n@example.com',
    avatar: 'https://picsum.photos/id/247/40/40',
    subject: 'Login issues on mobile app',
    body: `Support Team,\n\nI'm unable to log in to the mobile application since the last update (v2.5.1). I keep getting an "Authentication Failed" error, even though my credentials are correct and I can log in on the web just fine. I'm using an iPhone 14 running iOS 17.\n\nThis is very disruptive. Please advise on how to resolve this.\n\nThanks,\nRajesh`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 150),
    sentiment: 'negative',
    priority: 'high',
    status: 'pending',
  },
  {
    id: '12',
    sender: 'Sathish Balan',
    email: 'sathish.b@example.com',
    avatar: 'https://picsum.photos/id/248/40/40',
    subject: 'Collaboration opportunity',
    body: `Hi there,\n\nMy name is Sathish, and I'm a content creator in the tech space. I'm very impressed with your product and I believe it would be a great fit for my audience. I'd love to explore a potential collaboration, perhaps a sponsored video or a review.\n\nMy media kit is attached. Let me know if you're interested in discussing this further.\n\nAll the best,\nSathish`,
    receivedAt: new Date(Date.now() - 1000 * 60 * 60 * 180),
    sentiment: 'positive',
    priority: 'medium',
    status: 'pending',
  },
];
